// <auto-generated />
using System;
using BudgetPlanner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(BudgetContext))]
    [Migration("20260903004657_AddAccountInflowFoundation")]
    partial class AddAccountInflowFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetPlanner.Models.AccountInflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PaycheckEvidenceRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "OwnerId")
                        .HasName("AK_AccountInflows_Id_OwnerId");

                    b.HasIndex("OwnerId", "Date");

                    b.ToTable("AccountInflows", t =>
                        {
                            t.HasCheckConstraint("CK_AccountInflow_Description", "length(btrim(\"Description\")) > 0");

                            t.HasCheckConstraint("CK_AccountInflow_PositiveAmount", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("BudgetPlanner.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BudgetPlanner.Models.BudgetLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LimitAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("MonthYear")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BudgetLimits");
                });

            modelBuilder.Entity("BudgetPlanner.Models.Commitment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AmountMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ExpectedAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("ExpectedDay")
                        .HasColumnType("integer");

                    b.Property<string>("ExpectedDayOfWeek")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("ExpectedMaximumAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("ExpectedMinimumAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("ExpectedMonth")
                        .HasColumnType("integer");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OriginAlgorithmVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("OriginEvidenceFingerprint")
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimingKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WindowAfterDays")
                        .HasColumnType("integer");

                    b.Property<int>("WindowBeforeDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "OwnerId")
                        .HasName("AK_Commitments_Id_OwnerId");

                    b.HasIndex("OwnerId", "OriginEvidenceFingerprint")
                        .IsUnique()
                        .HasDatabaseName("UX_Commitments_Owner_OriginFingerprint")
                        .HasFilter("\"OriginEvidenceFingerprint\" IS NOT NULL");

                    b.ToTable("Commitments", t =>
                        {
                            t.HasCheckConstraint("CK_Commitment_Amount", "(\"AmountMode\" = 'Fixed' AND \"ExpectedAmount\" IS NOT NULL AND \"ExpectedAmount\" > 0 AND \"ExpectedMinimumAmount\" IS NULL AND \"ExpectedMaximumAmount\" IS NULL) OR (\"AmountMode\" = 'Range' AND \"ExpectedAmount\" IS NULL AND \"ExpectedMinimumAmount\" IS NOT NULL AND \"ExpectedMinimumAmount\" > 0 AND \"ExpectedMaximumAmount\" IS NOT NULL AND \"ExpectedMaximumAmount\" >= \"ExpectedMinimumAmount\")");

                            t.HasCheckConstraint("CK_Commitment_Enums", "\"Lifecycle\" IN ('Active', 'Paused', 'Ended') AND \"Cadence\" IN ('Weekly', 'Monthly', 'Yearly') AND \"TimingKind\" IN ('Weekday', 'DayOfMonth', 'MonthEnd', 'MonthAndDay') AND \"AmountMode\" IN ('Fixed', 'Range')");

                            t.HasCheckConstraint("CK_Commitment_Origin", "(\"OriginAlgorithmVersion\" IS NULL AND \"OriginEvidenceFingerprint\" IS NULL) OR (\"OriginAlgorithmVersion\" IS NOT NULL AND length(btrim(\"OriginAlgorithmVersion\")) > 0 AND \"OriginEvidenceFingerprint\" IS NOT NULL AND octet_length(\"OriginEvidenceFingerprint\") = 32)");

                            t.HasCheckConstraint("CK_Commitment_Text", "length(btrim(\"Name\")) > 0 AND length(btrim(\"Category\")) > 0");

                            t.HasCheckConstraint("CK_Commitment_Timestamps", "\"UpdatedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_Commitment_Timing", "(\"Cadence\" = 'Weekly' AND \"TimingKind\" = 'Weekday' AND \"ExpectedDayOfWeek\" IS NOT NULL AND \"ExpectedDayOfWeek\" IN ('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') AND \"ExpectedDay\" IS NULL AND \"ExpectedMonth\" IS NULL) OR (\"Cadence\" = 'Monthly' AND \"TimingKind\" = 'DayOfMonth' AND \"ExpectedDayOfWeek\" IS NULL AND \"ExpectedDay\" IS NOT NULL AND \"ExpectedDay\" BETWEEN 1 AND 31 AND \"ExpectedMonth\" IS NULL) OR (\"Cadence\" = 'Monthly' AND \"TimingKind\" = 'MonthEnd' AND \"ExpectedDayOfWeek\" IS NULL AND \"ExpectedDay\" IS NULL AND \"ExpectedMonth\" IS NULL) OR (\"Cadence\" = 'Yearly' AND \"TimingKind\" = 'MonthAndDay' AND \"ExpectedDayOfWeek\" IS NULL AND \"ExpectedMonth\" IS NOT NULL AND \"ExpectedMonth\" BETWEEN 1 AND 12 AND \"ExpectedDay\" IS NOT NULL AND \"ExpectedDay\" BETWEEN 1 AND CASE WHEN \"ExpectedMonth\" = 2 THEN 29 WHEN \"ExpectedMonth\" IN (4, 6, 9, 11) THEN 30 ELSE 31 END)");

                            t.HasCheckConstraint("CK_Commitment_Windows", "\"WindowBeforeDays\" >= 0 AND \"WindowAfterDays\" >= 0");
                        });
                });

            modelBuilder.Entity("BudgetPlanner.Models.CommitmentCandidateDismissal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EvidenceFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "AlgorithmVersion", "Cadence", "EvidenceFingerprint")
                        .IsUnique()
                        .HasDatabaseName("UX_CandidateDismissals_Owner_Origin");

                    b.ToTable("CommitmentCandidateDismissals", t =>
                        {
                            t.HasCheckConstraint("CK_CommitmentCandidateDismissal_AlgorithmVersion", "length(btrim(\"AlgorithmVersion\")) > 0");

                            t.HasCheckConstraint("CK_CommitmentCandidateDismissal_Cadence", "\"Cadence\" IN ('Weekly', 'Monthly', 'Yearly')");

                            t.HasCheckConstraint("CK_CommitmentCandidateDismissal_FingerprintLength", "octet_length(\"EvidenceFingerprint\") = 32");
                        });
                });

            modelBuilder.Entity("BudgetPlanner.Models.CommitmentChangeDismissal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CommitmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EvidenceFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommitmentId", "OwnerId");

                    b.HasIndex("OwnerId", "CommitmentId")
                        .HasDatabaseName("IX_CommitmentChangeDismissals_Owner_Commitment");

                    b.HasIndex("OwnerId", "CommitmentId", "AlgorithmVersion", "Dimension", "EvidenceFingerprint")
                        .IsUnique()
                        .HasDatabaseName("UX_CommitmentChangeDismissals_Owner_Assessment");

                    b.ToTable("CommitmentChangeDismissals", t =>
                        {
                            t.HasCheckConstraint("CK_CommitmentChangeDismissal_AlgorithmVersion", "length(btrim(\"AlgorithmVersion\")) > 0");

                            t.HasCheckConstraint("CK_CommitmentChangeDismissal_Dimension", "\"Dimension\" IN ('Amount', 'Timing', 'Missing')");

                            t.HasCheckConstraint("CK_CommitmentChangeDismissal_FingerprintLength", "octet_length(\"EvidenceFingerprint\") = 32");
                        });
                });

            modelBuilder.Entity("BudgetPlanner.Models.CommitmentOccurrence", b =>
                {
                    b.Property<Guid>("CommitmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExpenseId")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CommitmentId", "ExpenseId");

                    b.HasIndex("ExpenseId")
                        .IsUnique();

                    b.ToTable("CommitmentOccurrences", t =>
                        {
                            t.HasCheckConstraint("CK_CommitmentOccurrence_Kind", "\"Kind\" = 'ConfirmationEvidence'");
                        });
                });

            modelBuilder.Entity("BudgetPlanner.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CommitmentEvidenceRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("BudgetPlanner.Models.ImportExpenseProvenance", b =>
                {
                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceRowOrdinal")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpenseId")
                        .HasColumnType("integer");

                    b.HasKey("BatchId", "SourceRowOrdinal");

                    b.HasIndex("ExpenseId")
                        .IsUnique()
                        .HasFilter("\"ExpenseId\" IS NOT NULL");

                    b.ToTable("ImportExpenseProvenances", t =>
                        {
                            t.HasCheckConstraint("CK_ImportExpenseProvenance_PositiveSourceRowOrdinal", "\"SourceRowOrdinal\" > 0");
                        });
                });

            modelBuilder.Entity("BudgetPlanner.Models.ImportInflowProvenance", b =>
                {
                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceRowOrdinal")
                        .HasColumnType("integer");

                    b.Property<int?>("AccountInflowId")
                        .HasColumnType("integer");

                    b.Property<string>("AccountInflowOwnerId")
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BatchId", "SourceRowOrdinal");

                    b.HasIndex("AccountInflowId")
                        .IsUnique()
                        .HasFilter("\"AccountInflowId\" IS NOT NULL");

                    b.HasIndex("AccountInflowId", "AccountInflowOwnerId");

                    b.HasIndex("BatchId", "OwnerId");

                    b.ToTable("ImportInflowProvenances", t =>
                        {
                            t.HasCheckConstraint("CK_ImportInflowProvenance_OwnerConsistency", "(\"AccountInflowId\" IS NULL AND \"AccountInflowOwnerId\" IS NULL) OR (\"AccountInflowId\" IS NOT NULL AND \"AccountInflowOwnerId\" IS NOT NULL AND \"AccountInflowOwnerId\" = \"OwnerId\")");

                            t.HasCheckConstraint("CK_ImportInflowProvenance_PositiveSourceRowOrdinal", "\"SourceRowOrdinal\" > 0");
                        });
                });

            modelBuilder.Entity("BudgetPlanner.Models.ImportPreviewBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("DocumentDigest")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParserRuleVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "OwnerId")
                        .HasName("AK_ImportPreviewBatches_Id_OwnerId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("OwnerId", "SourceType", "DocumentDigest")
                        .IsUnique()
                        .HasFilter("\"Lifecycle\" = 'Open'");

                    b.HasIndex(new[] { "OwnerId", "SourceType", "ParserRuleVersion", "DocumentDigest" }, "IX_ImportPreviewBatches_ActiveDocument")
                        .IsUnique()
                        .HasDatabaseName("IX_ImportPreviewBatches_ActiveDocument")
                        .HasFilter("\"Lifecycle\" IN ('Open', 'Confirmed')");

                    b.HasIndex(new[] { "OwnerId", "SourceType", "ParserRuleVersion", "DocumentDigest" }, "IX_ImportPreviewBatches_ConfirmedDocument")
                        .IsUnique()
                        .HasDatabaseName("IX_ImportPreviewBatches_ConfirmedDocument")
                        .HasFilter("\"Lifecycle\" = 'Confirmed'");

                    b.ToTable("ImportPreviewBatches", t =>
                        {
                            t.HasCheckConstraint("CK_ImportPreviewBatch_ConfirmedAt", "(\"Lifecycle\" = 'Confirmed' AND \"ConfirmedAt\" IS NOT NULL) OR (\"Lifecycle\" <> 'Confirmed' AND \"ConfirmedAt\" IS NULL)");

                            t.HasCheckConstraint("CK_ImportPreviewBatch_DigestLength", "octet_length(\"DocumentDigest\") = 32");

                            t.HasCheckConstraint("CK_ImportPreviewBatch_Expiry", "\"ExpiresAt\" > \"CreatedAt\"");

                            t.HasCheckConstraint("CK_ImportPreviewBatch_SourceType", "\"SourceType\" = 'sunflower_pdf'");
                        });
                });

            modelBuilder.Entity("BudgetPlanner.Models.ImportPreviewRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DuplicateExpenseIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EditableExpenseDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPossibleDuplicate")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("PostedDate")
                        .HasColumnType("date");

                    b.Property<bool>("SelectedForImport")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SourcePageNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SourceRowOrdinal")
                        .HasColumnType("integer");

                    b.Property<string>("SourceSection")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ValidationErrorCodes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("WarningCodes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "SourceRowOrdinal")
                        .IsUnique();

                    b.ToTable("ImportPreviewRows", t =>
                        {
                            t.HasCheckConstraint("CK_ImportPreviewRow_PositiveAmount", "\"Amount\" IS NULL OR \"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BudgetPlanner.Models.AccountInflow", b =>
                {
                    b.HasOne("BudgetPlanner.Models.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BudgetPlanner.Models.BudgetLimit", b =>
                {
                    b.HasOne("BudgetPlanner.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetPlanner.Models.Commitment", b =>
                {
                    b.HasOne("BudgetPlanner.Models.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BudgetPlanner.Models.CommitmentCandidateDismissal", b =>
                {
                    b.HasOne("BudgetPlanner.Models.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BudgetPlanner.Models.CommitmentChangeDismissal", b =>
                {
                    b.HasOne("BudgetPlanner.Models.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetPlanner.Models.Commitment", "Commitment")
                        .WithMany()
                        .HasForeignKey("CommitmentId", "OwnerId")
                        .HasPrincipalKey("Id", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commitment");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BudgetPlanner.Models.CommitmentOccurrence", b =>
                {
                    b.HasOne("BudgetPlanner.Models.Commitment", "Commitment")
                        .WithMany("Occurrences")
                        .HasForeignKey("CommitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetPlanner.Models.Expense", "Expense")
                        .WithMany()
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commitment");

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("BudgetPlanner.Models.Expense", b =>
                {
                    b.HasOne("BudgetPlanner.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetPlanner.Models.ImportExpenseProvenance", b =>
                {
                    b.HasOne("BudgetPlanner.Models.ImportPreviewBatch", "Batch")
                        .WithMany("Provenance")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetPlanner.Models.Expense", "Expense")
                        .WithMany()
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Batch");

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("BudgetPlanner.Models.ImportInflowProvenance", b =>
                {
                    b.HasOne("BudgetPlanner.Models.AccountInflow", "AccountInflow")
                        .WithMany()
                        .HasForeignKey("AccountInflowId", "AccountInflowOwnerId")
                        .HasPrincipalKey("Id", "OwnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ImportInflowProvenance_AccountInflow_Owner");

                    b.HasOne("BudgetPlanner.Models.ImportPreviewBatch", "Batch")
                        .WithMany("InflowProvenance")
                        .HasForeignKey("BatchId", "OwnerId")
                        .HasPrincipalKey("Id", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ImportInflowProvenance_Batch_Owner");

                    b.Navigation("AccountInflow");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("BudgetPlanner.Models.ImportPreviewBatch", b =>
                {
                    b.HasOne("BudgetPlanner.Models.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BudgetPlanner.Models.ImportPreviewRow", b =>
                {
                    b.HasOne("BudgetPlanner.Models.ImportPreviewBatch", "Batch")
                        .WithMany("Rows")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BudgetPlanner.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BudgetPlanner.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetPlanner.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BudgetPlanner.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetPlanner.Models.Commitment", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("BudgetPlanner.Models.ImportPreviewBatch", b =>
                {
                    b.Navigation("InflowProvenance");

                    b.Navigation("Provenance");

                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
